import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from '@clerk/nextjs'


const IBMPlex = IBM_Plex_Sans({ 
  subsets: ["latin"],
  weight: ['400', '700'],
  variable:'--font-ibm-plex',
});

export const metadata: Metadata = {
  title: "ImageGen",
  description: "",
>>>>>>> 634b91f (commit_message)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
=======
    <ClerkProvider appearance={{
      variables: { colorPrimary: "#624cf5" }
    }}>
      <html lang="en">
        <body className={cn("font-IBMPlex antialiased, IBMPlex.variable")}>
          {children}
          </body>
      </html>
    </ClerkProvider>
>>>>>>> 634b91f (commit_message)
  );
}
